<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accounting ID' => '',
    'Apply Time' => '',
    'Article' => 'Артикул',
    'Binary' => '',
    'Count' => '',
    'Created At' => '',
    'Currency' => 'Валюта',
    'Data' => '',
    'Description' => 'Описание',
    'Extension' => '',
    'Folder' => '',
    'Group ID' => '',
    'ID' => '',
    'Image ID' => '',
    'Is Active' => '',
    'Is Exist' => '',
    'Md5' => '',
    'Mime Type' => '',
    'Name' => 'Наименование',
    'Offer ID' => '',
    'Order ID' => '',
    'Parent ID' => '',
    'Performance' => 'Представление',
    'Price ID' => '',
    'Price Type ID' => '',
    'Product ID' => '',
    'Property ID' => '',
    'Property Value ID' => '',
    'Rate' => 'Коэффициент',
    'Remnant' => 'Остаток',
    'Requisite ID' => '',
    'Session' => '',
    'Size' => '',
    'Slug' => '',
    'Specification ID' => '',
    'Status ID' => '',
    'Sum' => 'Сумма',
    'Type ID' => '',
    'Uid' => '',
    'Updated At' => '',
    'User ID' => '',
    'Value' => 'Значение',
    'Version' => '',
    'Warehouse ID' => '',
];
